"""empty message

Revision ID: 0edd3db22e79
Revises: 7975e7714ccf
Create Date: 2024-06-20 01:04:45.310784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0edd3db22e79'
down_revision = '7975e7714ccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Sanitario', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Rubro', ['rubro_id'], ['id'])
        batch_op.drop_column('rubro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Sanitario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rubro', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
