"""Remove duplicate rubro_id column

Revision ID: 292ae4dff00c
Revises: 0edd3db22e79
Create Date: 2024-06-20 01:17:41.677854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '292ae4dff00c'
down_revision = '0edd3db22e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Sanitario', schema=None) as batch_op:
        batch_op.drop_column('rubro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Sanitario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rubro', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
