"""add filed to sanitario

Revision ID: 32db0d1f556f
Revises: 28473610335a
Create Date: 2024-06-17 18:51:56.332719

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32db0d1f556f'
down_revision = '28473610335a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ConsumoSanitario', schema=None) as batch_op:
        batch_op.drop_column('saldo')

    with op.batch_alter_table('Sanitario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo', sa.Double(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Sanitario', schema=None) as batch_op:
        batch_op.drop_column('saldo')

    with op.batch_alter_table('ConsumoSanitario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo', mysql.DOUBLE(asdecimal=True), nullable=True))

    # ### end Alembic commands ###
