"""add table rubro

Revision ID: 7975e7714ccf
Revises: 32db0d1f556f
Create Date: 2024-06-20 00:33:03.710071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7975e7714ccf'
down_revision = '32db0d1f556f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Sanitario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rubro_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'Rubro', ['rubro_id'], ['id'])
        batch_op.drop_column('rubro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Sanitario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rubro', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rubro_id')

    # ### end Alembic commands ###
