"""update migrate

Revision ID: b690c7267613
Revises: b8cb58ec5478
Create Date: 2024-06-27 07:43:33.468246

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b690c7267613'
down_revision = 'b8cb58ec5478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingreso_insumo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insumo_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_ingreso_insumo_vacuna_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_ingreso_insumo_insumo_id', 'Insumo', ['insumo_id'], ['id'])
        batch_op.drop_column('Insumo_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingreso_insumo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Insumo_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint('fk_ingreso_insumo_insumo_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_ingreso_insumo_vacuna_id', 'Insumo', ['Insumo_id'], ['id'])
        batch_op.drop_column('insumo_id')

    # ### end Alembic commands ###
