"""add activo

Revision ID: b8cb58ec5478
Revises: dddcb44669f7
Create Date: 2024-06-20 06:43:35.314226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8cb58ec5478'
down_revision = 'dddcb44669f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ConsumoSanitario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    with op.batch_alter_table('IngresoxEgreso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('IngresoxEgreso', schema=None) as batch_op:
        batch_op.drop_column('activo')

    with op.batch_alter_table('ConsumoSanitario', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
