"""add insumo

Revision ID: dddcb44669f7
Revises: 292ae4dff00c
Create Date: 2024-06-20 04:46:49.455475

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dddcb44669f7'
down_revision = '292ae4dff00c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('IngresoxEgreso', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('IngresoxEgreso', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
